### ISSUE TITLE
Force into Format Type 0 possible?

### ISSUE THREAD

**Issue by mohanklein** [jimm/midilib#30]
Hey Jimm!

Is there a straight forward way to force a file/sequence into Format Type 0 using midilib? See attached an example binary structure of a Type 1 file with multiple tracks. Is there a way to force this into Type 0 with only 1 track without losing data? Sorry can't really find this in the docs.

Love from Germany
Mohan

<img width="261" alt="Bildschirmfoto 2024-02-19 um 16 03 56" src="https://github.com/jimm/midilib/assets/7778513/84a90b15-7698-4042-a135-0e89666408bc">

**Comment by jimm** [comment]
@mohanklein The [Sequence.write](https://github.com/jimm/midilib/blob/main/lib/midilib/sequence.rb#L148) method takes a second optional parameter that is the MIDI file format. Only 0 and 1 are supported, but if you pass in 0 then it will output a type 0 MIDI file.

**Comment by mohanklein** [comment]
@jimm This does force my test file into MIDI Format Type 0 but it seems in my test midi file all Note Events are now turned into repeatBits as children of a single NoteOn Event which seems wrong? Is this a desired behavior? Please see compare screens from "Synalyze It" Hex Editor compared.

I used this "Grammar" inside "Synalyze It" Hex Editor: https://raw.githubusercontent.com/synalysis/Grammars/master/midi.grammar
which states to implement this MIDI spec:
http://www.somascape.org/midi/tech/mfile.html

<img width="317" alt="org" src="https://github.com/jimm/midilib/assets/7778513/4bf51c00-c333-489d-a67e-1e2d950033f9">
<img width="401" alt="converted" src="https://github.com/jimm/midilib/assets/7778513/0d1925a3-ee81-4ff0-b3fe-04422b9fbf69">

**Comment by mohanklein** [comment]
@jimm another screen showing only one single real Note On event is left - after using midilib ...
<img width="286" alt="Bildschirmfoto 2024-02-20 um 14 43 58" src="https://github.com/jimm/midilib/assets/7778513/0a9c0086-bdfa-43d6-975f-2a743628de3d">

**Comment by jimm** [comment]
@mohanklein Hmm, you might have found a bug that the tests don't catch. Are you able to send me both MIDI files and whatever code you used to read the original file and output the Type 0 file?

**Comment by mohanklein** [comment]
@jimm I just tested this with another file and a "placebo" code not touching the midi other than forcing to type 0: same result. Attached in the zip file:
- an original type 1 file with multiple Note Events
- the processed type 0 file (after the midilib placebo code) having lots of repeatBit children for one Note On Event instead

```
#!/usr/bin/env ruby

require 'midilib'

class Processor
  def self.run
    seq = MIDI::Sequence.new()

    File.open('org.mid', 'rb') { |file|
      seq.read(file)
    }

    seq.each { |track|
      track.each { |event|
        # Don't do anything :-)
      }
    }

    File.open('processed.mid', 'wb') { |file| seq.write(file, 0) }
  end
end

Processor::run
```

[midilib-format-type-bug.zip](https://github.com/jimm/midilib/files/14346287/midilib-format-type-bug.zip)

<img width="332" alt="org" src="https://github.com/jimm/midilib/assets/7778513/90fc0272-98f3-4296-b313-7b2a417d6ec9">
<img width="274" alt="processed" src="https://github.com/jimm/midilib/assets/7778513/4866cd8e-b132-4b10-b072-1e7399685e5a">

**Comment by jimm** [comment]
Thank you, @mohanklein . I'll try to get to this bug, but I'm afraid I don't know how quick I'll be able to attack it.

**Comment by mohanklein** [comment]
hey @jimm! I just took another look into this and used the old version 2.0.5 which did not yet have the midi_file_format attribute for the sequence write method. The processed format type 1 file will have the same problem though (repeatBits and only one Note Event). Maybe this helps narrowing this bug problem down!

**Comment by jimm** [comment]
Thanks, that does help. I actually think that this isn't a bug (but I want to prove it as soon as I have time). I think it has to do with the fact that all of the note off messages in the original file are note on messages with a zero velocity. That is perfectly legal --- the MIDI spec says that note on messages with a zero velocity are the same as note off messages. This allows the MIDI to be compressed by outputting running status bytes, which I _think_ are what those "repeat" messages are in the output you're displaying. Running status bytes means that if the same status byte would be repeated then it can be omitted. midilib does that when writing its output.

In fact, the issue describe with all of the notes being a "child" of one note on message might be perfectly correct. The first thing I have to do when I get to this is determine if the output you are seeing in fact perfectly legal and correct. There might not be any bug here. The output file is 96 bytes shorter than the input file, and I think that is due to midilib compressing the output by using running status messages.

Have you tried playing the file? Does it sound right?

**Comment by jimm** [comment]
I just re-processed the processed file, and the output is exactly the same. Even when the output type is switched, that doesn't make a difference --- the only difference in the two files is the single byte that stores the file type number. So at least midilib is being consistent :-)

**Comment by mohanklein** [comment]
Hey @jimm the org.mid file from the archive zip seems to have a strange structure (it is from a MIDI vendor I closely work together with). All their MIDI files have the same problem: When using them inside the drum software "Toontrack Superior Drummer" they will show up with a lot of more bars then the notes actually have, e.g. a 4 bar drum groove would show up as 4410 bars inside "Superior Drummer".  When using midilib version 2.0.5 (until last summer when you fixed the note on 0 veloctiy behavior which I had found) the org.mid file from the zip archive would show the correct amount of bars inside "Superior Drummer" after running it through midilib. With the current version 4.0.2 this is no longer the case. That is why I looked into this and found this behavior. Attached a screenshot showing my original problem with the original "strange" MIDI files showing a lot of bars inside "Superior Drummer" and the processed v2 file which shows the correct amount of 4 bars and the processed v4 file which "keeps the bar problem". I do not know what exactly is going on inside "Superior Drummer" as I don't work with them - when I drag the "problematic" MIDI files directly to any DAW they are fine and only have the correct bars, e.g. 4. Attached also the org.mid and after conversion with midilib 2 and 4.

<img width="1590" alt="Bildschirmfoto 2024-02-21 um 15 50 19" src="https://github.com/jimm/midilib/assets/7778513/1bf3d120-2126-45f8-a3ef-10e51ee80f12">

[Archiv.zip](https://github.com/jimm/midilib/files/14361057/Archiv.zip)

**Comment by mohanklein** [comment]
so manipulating that end of track event's delta time is the solution to "fix" those files? is the end of track event mandatory for the meta track 1?

**Comment by jimm** [comment]
I'm not sure about version 2.0.5, but the method that adds an end of track event if it is missing was added early last year so all tracks that midilib outputs will have them. I believe end of track event is optional. If you remove that end of track event or fix it, you should be all good.

**Comment by mohanklein** [comment]
@jimm I don't think this explains the difference in behavior with the strange meta delta time file though ...

**Comment by jimm** [comment]
You could always use midilib to erase that "bad" end of track meta event before writing out the data, and then when the data gets written out midilib would add one that's based on the last note instead of being 4410 bars out.

**Comment by jimm** [comment]
That looks good. Since every track can have an end of track meta event, you probably shouldn't filter by track index. And you could optionally remove the event instead of changing the delta time. The end result should be the same.

To remove an event, you can call `track.delete_event(event)`. If you're sure the event is the last event in the track already, you can pass in a `calc_recalc_times` value of `false` (that is, `track.delete_event(event, false)`) to avoid recalculating all of the events' start times. Those are calculated off of the delta times and they are ignored when writing out the data.

**Comment by jimm** [comment]
By the way, the `delete_event` method takes care of fixing the delta time of the following event if there is one. So you don't have to worry about that.

**Comment by mohanklein** [comment]
thanks jimm!!!
